<?php

return [
    'ups' => [
        'api_integration' => env('UPS_API_INTEGRATION', false),
        'api_env' => env('UPS_SHIPPING_API_ENV', 'dev'),
        'url_dev' => "https://wwwcie.ups.com/rest/",
        'url_prod' => "https://onlinetools.ups.com/rest/",
        'api_user' => env('UPS_API_USER', ""),
        'api_password' => env('UPS_API_PASSWORD', ""),
        'access_token' => env('UPS_API_ACCESS_TOKEN', ""),
        'account_number' => env('UPS_API_ACCOUNT_NUMBER', ""),

        'shipper_address' => [
            'address' => env('UPS_API_USER_ADDRESS', ''),
            'city' => env('UPS_API_USER_CITY', ''),
            'zip' => env('UPS_API_USER_ZIP', ''),
            'state' => env('UPS_API_USER_STATE', ''),
            'country' => env('UPS_API_USER_COUNTRY', ''),
        ],

        'services' => [
            '01' => 'UPS Next Day Air',
            '02' => 'UPS 2nd Day Air',
            '03' => 'UPS Ground',
            '07' => 'UPS Express',
            '08' => 'UPS Expedited',
            '11' => 'UPS Standard',
            '12' => 'UPS 3 Day Select',
            '13' => 'UPS Next Day Saver',
            '14' => 'UPS Next Day Air Early',
            '54' => 'UPS Express Plus',
            '59' => 'UPS 2nd Day Air A.M',
            '65' => 'UPS Saver',
            '70' => 'UPS Access Point™ Economy',
            'M2' => 'UPS First Class Mail',
            'M3' => 'UPS Priority Mail',
            'M4' => 'UPS Expedited Mail Innovations',
            'M5' => 'UPS Priority Mail Innovations',
            'M6' => 'UPS Economy Mail Innovations',
            'M7' => 'UPS Mail Innovations (MI) Returns',
            '70' => 'UPS Access Point™ Economy',
            '71' => 'UPS Worldwide Express Freight Midday',
            '74' => 'UPS Express®12:00',
            '82' => 'UPS Today Standard',
            '83' => 'UPS Today Dedicated Courier',
            '84' => 'UPS Today Intercity',
            '85' => 'UPS Today Express',
            '86' => 'UPS Today Express Saver',
            '96' => 'UPS Worldwide Express Freight'
        ],
        
        'services_allowed' => explode(',', env('UPS_SERVICES_ALLOWED', '03,14,01,13,59,02,12')),

        'package_types' => [
            '01' => 'UPS Letter',
            '02' => 'Customer Supplied Package',
            '03' => 'Tube',
            '04' => 'PAK',
            '21' => 'UPS Express Box',
            '24' => 'UPS 25KG Box',
            '25' => 'UPS 10KG Box',
            '30' => 'Pallet',
            '2a' => 'Small Express Box',
            '2b' => 'Medium Express Box',
            '2c' => 'Large Express Box',
            '56' => 'Flats',
            '57' => 'Parcels',
            '58' => 'BPM',
            '59' => 'First Class',
            '60' => 'Priority',
            '61' => 'Machinables',
            '62' => 'Irregulars',
            '63' => 'Parcel Post',
            '64' => 'BPM Parcel',
            '65' => 'Media Mail',
            '66' => 'BPM Flat',
            '67' => 'Standard Flat',
        ],
    ]
];
